import React from "react";
import jsPDF from "jspdf";

export default function ViewInvoiceModal({ invoice, onClose }) {
  if (!invoice) return null;

  const handleExportPDF = () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });

    let y = 20;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("Invoicify", 14, y);
    y += 10;

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Invoice #: ${invoice.invoiceNumber}`, 14, y);
    y += 6;
    doc.text(`Status: ${invoice.status}`, 14, y);

    y += 12;
    doc.setFont("helvetica", "bold");
    doc.text("Bill To:", 14, y);
    doc.setFont("helvetica", "normal");
    y += 6;
    doc.text(invoice.client.name || "", 14, y);
    y += 6;
    doc.text(invoice.client.email || "", 14, y);

    if (invoice.client.address) {
      const a = invoice.client.address;
      y += 6;
      doc.text(
        `${a.street || ""}, ${a.city || ""}, ${a.state || ""} ${a.postalCode || ""}`,
        14,
        y
      );
      y += 6;
      doc.text(`${a.country || ""}`, 14, y);
    }

    const invDate = new Date(invoice.invoiceDate).toLocaleDateString();
    const dueDate = new Date(invoice.dueDate).toLocaleDateString();
    doc.text(`Invoice Date: ${invDate}`, 120, 50);
    doc.text(`Due Date: ${dueDate}`, 120, 56);

    // Table Header
    y = 85;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Description", 14, y);
    doc.text("Qty", 105, y, { align: "right" });
    doc.text("Unit", 130, y, { align: "right" });
    doc.text("Tax", 155, y, { align: "right" });
    doc.text("Total", 190, y, { align: "right" });
    y += 2;
    doc.setDrawColor(180);
    doc.line(14, y, 196, y);

    // Table Rows
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    y += 6;
    invoice.items.forEach((item) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }
      doc.text(item.description, 14, y);
      doc.text(String(item.quantity), 105, y, { align: "right" });
      doc.text(`Rs ${item.unitPrice.toFixed(2)}`, 130, y, { align: "right" });
      doc.text(`${item.taxRate}%`, 155, y, { align: "right" });
      doc.text(`Rs ${item.total.toFixed(2)}`, 190, y, { align: "right" });
      y += 6;
    });

    // Totals
    y += 4;
    doc.setDrawColor(200);
    doc.line(130, y, 190, y);
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Subtotal:", 140, y);
    doc.text(`Rs ${invoice.subTotal.toFixed(2)}`, 190, y, { align: "right" });
    y += 6;
    doc.text("Tax Total:", 140, y);
    doc.text(`Rs ${invoice.taxTotal.toFixed(2)}`, 190, y, { align: "right" });
    if (invoice.discount > 0) {
      y += 6;
      doc.text("Discount:", 140, y);
      doc.text(`-Rs ${invoice.discount.toFixed(2)}`, 190, y, { align: "right" });
    }
    y += 8;
    doc.setFontSize(12);
    doc.text("Total:", 140, y);
    doc.text(`Rs ${invoice.total.toFixed(2)}`, 190, y, { align: "right" });

    // Notes
    if (invoice.notes) {
      y += 12;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text("Notes:", 14, y);
      y += 6;
      doc.setFont("helvetica", "normal");
      const wrapped = doc.splitTextToSize(invoice.notes, 180);
      doc.text(wrapped, 14, y);
      y += wrapped.length * 5;
    }

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text("Generated by Invoicify", 14, 285);
    doc.text(
      `Created: ${new Date(invoice.createdAt || Date.now()).toLocaleString()}`,
      150,
      285
    );

    doc.save(`Invoice_${invoice.invoiceNumber}.pdf`);
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-30 flex items-center justify-center z-50">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-3xl p-8 relative overflow-y-auto max-h-[90vh]">
        <div className="flex justify-between items-start mb-6">
          <div>
            <h2 className="text-2xl font-semibold text-gray-900">
              Invoice {invoice.invoiceNumber}
            </h2>
            <p className="text-sm text-gray-500 capitalize">
              Status: {invoice.status}
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-800 text-lg font-semibold"
          >
            ✕
          </button>
        </div>

        <div className="mb-6 border-b border-gray-200 pb-4">
          <h3 className="text-sm font-medium text-gray-700 mb-2">Client</h3>
          <div className="text-sm text-gray-600">
            <p>{invoice.client.name}</p>
            <p>{invoice.client.email}</p>
            {invoice.client.address && (
              <p>
                {invoice.client.address.street}, {invoice.client.address.city},{" "}
                {invoice.client.address.state} {invoice.client.address.postalCode},{" "}
                {invoice.client.address.country}
              </p>
            )}
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4 mb-6">
          <div>
            <p className="text-sm text-gray-500">Invoice Date</p>
            <p className="text-gray-800 font-medium">
              {new Date(invoice.invoiceDate).toLocaleDateString()}
            </p>
          </div>
          <div>
            <p className="text-sm text-gray-500">Due Date</p>
            <p className="text-gray-800 font-medium">
              {new Date(invoice.dueDate).toLocaleDateString()}
            </p>
          </div>
        </div>

        <div className="mb-6">
          <h3 className="text-sm font-medium text-gray-700 mb-2">Items</h3>
          <div className="overflow-x-auto border border-gray-200 rounded-lg">
            <table className="min-w-full text-sm text-gray-700">
              <thead className="bg-gray-100 text-gray-600 uppercase text-xs">
                <tr>
                  <th className="px-4 py-2 text-left">Description</th>
                  <th className="px-4 py-2 text-center">Qty</th>
                  <th className="px-4 py-2 text-right">Unit Price</th>
                  <th className="px-4 py-2 text-right">Tax</th>
                  <th className="px-4 py-2 text-right">Total</th>
                </tr>
              </thead>
              <tbody>
                {invoice.items.map((item, idx) => (
                  <tr key={idx} className="border-t border-gray-100">
                    <td className="px-4 py-2">{item.description}</td>
                    <td className="px-4 py-2 text-center">{item.quantity}</td>
                    <td className="px-4 py-2 text-right">
                      Rs {item.unitPrice.toFixed(2)}
                    </td>
                    <td className="px-4 py-2 text-right">{item.taxRate}%</td>
                    <td className="px-4 py-2 text-right">
                      Rs {item.total.toFixed(2)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className="flex justify-end mb-8">
          <div className="w-64 space-y-2 text-sm text-gray-700">
            <div className="flex justify-between">
              <span>Subtotal:</span>
              <span>Rs {invoice.subTotal.toFixed(2)}</span>
            </div>
            <div className="flex justify-between">
              <span>Tax Total:</span>
              <span>Rs {invoice.taxTotal.toFixed(2)}</span>
            </div>
            {invoice.discount > 0 && (
              <div className="flex justify-between">
                <span>Discount:</span>
                <span>-Rs {invoice.discount.toFixed(2)}</span>
              </div>
            )}
            <div className="flex justify-between font-semibold border-t border-gray-200 pt-2">
              <span>Total:</span>
              <span>Rs {invoice.total.toFixed(2)}</span>
            </div>
          </div>
        </div>

        <div className="flex justify-end gap-3">
          <button
            onClick={onClose}
            className="px-4 py-2 text-gray-600 border border-gray-300 rounded-lg hover:bg-gray-100 transition"
          >
            Close
          </button>
          <button
            onClick={handleExportPDF}
            className="px-4 py-2 bg-blue-600 text-black rounded-lg hover:bg-blue-700 transition"
          >
            Export as PDF
          </button>
        </div>
      </div>
    </div>
  );
}
